<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AuthorizationServer.Models</AssemblyName>
    <RootNamespace>AuthorizationServer.Models</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="EdgeDb\" />
  </ItemGroup>

</Project>
